export const AuthActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGIN_LOADING: 'LOGIN_LOADING',
    ERROR_LOGIN_USER: 'ERROR_LOGIN_USER',
    REGISTER_SUCCES: 'REGISTER_SUCCES',
}